Make TimeParameterization classes polymorphic
ros-planning/moveit2 pull request #1012
Opened 2022-01-18 23:48 UTC by JafarAbdi

### Description

Cherry-pick https://github.com/ros-planning/moveit/pull/3021 in moveit2

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

2022-01-20 18:24 UTC, stephanie-eng approved these changes

2022-01-24 14:12 UTC, AndyZe approved these changes

2022-01-27 14:17 UTC, henningkayser approved these changes
Is this too urgent so that we can't wait for this to get synced? Good change, imo

2022-01-27 14:17 UTC, henningkayser commented on moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_parameterization.h
> +#pragma once
license header?

2022-01-31 12:26 UTC, jliukkonen requested changes
Not sure if I can actually block merging on my own but I'm marking this as "request changes" until there are comments. Otherwise it's too easy to forget them :)

2022-04-04 23:38 UTC, JafarAbdi commented
Replace with https://github.com/ros-planning/moveit2/pull/1151

2022-04-04 23:38 UTC, closed without merging