pointcloud_octomap_updater: Don't return false when not finding optional parameter
ros-planning/moveit2 pull request #1418
Opened 2022-07-07 19:19 UTC by JafarAbdi

### Description

It was causing the function to return false even if we are missing an optinal parameter

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

2022-07-18 17:02 UTC, tylerjw requested changes
I think you must have accidentally included a bunch of version bumps in this?

2022-07-18 17:02 UTC, tylerjw commented on moveit/package.xml
> -  <version>2.5.1</version>
?

2022-07-21 14:56 UTC, MarqRazz approved these changes
This fixes errors on my system running Humble.

2022-07-21 15:01 UTC, AndyZe commented on moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp
> +  node_->get_parameter_or(name_space + ".ns", ns_, std::string());
Please add a comment here so we can follow this logic in the future.

```suggestion
  // This parameter is optional
  node_->get_parameter_or(name_space + ".ns", ns_, std::string());
```

2022-07-21 23:02 UTC, AndyZe approved these changes

2022-07-25 22:39 UTC, vatanaksoytezer approved these changes

2022-07-26 12:31 UTC, tylerjw approved these changes

2022-07-26 12:31 UTC, merged