Unit test LinearPathSegment
ros-planning/moveit2 pull request #1792
Opened 2022-12-07 19:57 UTC by tylerjw

### Description

This pull request adds tests and documentation to the LinearPathSegment class. The tests check that the constructor works correctly, that the getConfig(), getTangent(), getCurvature(), and getSwitchingPoints() methods return the expected results, and that the clone() method creates a deep copy. The documentation provides a description of the class and detailed descriptions of all the public methods.

2022-12-07 22:25 UTC, ChrisThrasher requested changes

2022-12-07 22:25 UTC, ChrisThrasher commented on moveit_core/trajectory_processing/test/test_linear_path_segment.cpp
> +  Eigen::VectorXd start(2);
Can we test with fixed size vectors or are those not convertible to the `Xd` variable-sized vectors?

2022-12-08 20:45 UTC, ChrisThrasher commented on moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
> -class LinearPathSegment : public PathSegment
So we're promoting `LinearPathSegment` from an implementation detail to a public interface? Are we sure we want to do that and start making guarantees on its stability?

2023-08-23 17:09 UTC, tylerjw commented
I'm closing this as I abandoned this work and did not finish it.

2023-08-23 17:09 UTC, closed without merging