Add extented World test for joint limits (#413)
ros-planning/moveit2 pull request #2074
Opened 2023-04-01 17:58 UTC by adeeb10abbas

Hi! First time contributor. All feedback is welcome! Thanks :) 
### Description

This PR adds an extended test case for the World class, focusing on joint limit parameters, joint velocity limits, and joint acceleration limits. The test case ensures that the RobotModelBuilder correctly sets joint limits and that the RobotState enforces these bounds as expected. Solves #413 

#### Test Case Overview
- [x] Set up a simple robot model using the RobotModelBuilder with two revolute joints and a single chain.
- [x] Define joint position, velocity, and acceleration limits for the robot model.
- [x] Load the robot model into a World object.
- [x] Create two RobotState objects with joint values, velocities, and accelerations.
- [x] Set joint values, velocities, and accelerations within the defined limits for the first RobotState.
- [x] Set joint values, velocities, and accelerations beyond the defined limits for the second RobotState.
- [x] Enforce joint position, velocity, and acceleration limits for the second RobotState.
- [x] Check that the joint values, velocities, and accelerations are within the defined limits after enforcement.
- [x] Verify that the joint limits have been applied correctly to the joint models.

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

2023-04-02 10:51 UTC, henningkayser commented
Thank you for these test cases. Why did you choose to add them to world? The test cases don't seem related at all.

2023-04-02 12:53 UTC, adeeb10abbas commented
@henningkayser Where should they go? I wasn't entirely clear on that

2023-04-03 19:19 UTC, henningkayser requested changes
Tests like these would belong next to RobotModel in moveit_core

2023-04-03 19:19 UTC, henningkayser commented on moveit_core/collision_detection/test/test_world.cpp
> +  builder.setJointLimits("joint1", { -M_PI, M_PI, 1.0, 2.0 });  // position, velocity, acceleration limits
where did you find this member function? Also, 4 values?

2023-04-03 19:19 UTC, henningkayser commented on moveit_core/collision_detection/test/test_world.cpp
> +    return TrackChangesNotify(ta, object, action);
what is happening here?

2023-04-04 10:55 UTC, henningkayser commented
doesn't compile, code doesn't make sense and is using non-existent functions.

2023-04-04 10:55 UTC, closed without merging