Galactic branch
ros-planning/moveit2 pull request #953
Opened 2022-01-03 15:21 UTC by henningkayser

Updates build badges and workflows for `galactic`

2022-01-03 15:48 UTC, JafarAbdi approved these changes

2022-01-03 18:37 UTC, vatanaksoytezer requested changes
@henningkayser we should use galactic branch of `ros2_control` and `ros2_controllers`.

2022-01-03 18:42 UTC, tylerjw commented
> @henningkayser we should use galactic branch of `ros2_control` and `ros2_controllers`.

I think we should depend on the released versions of ros2_control on our galactic branch.

2022-01-03 18:44 UTC, vatanaksoytezer commented
> I think we should depend on the released versions of ros2_control on our galactic branch.

Should've written that way, that's more accurate.

2022-01-03 18:53 UTC, henningkayser commented
> > @henningkayser we should use galactic branch of `ros2_control` and `ros2_controllers`.
> 
> I think we should depend on the released versions of ros2_control on our galactic branch.

We do that already, no? `ros2_control` is not listed inside `moveit2.repos`

2022-01-03 19:04 UTC, vatanaksoytezer commented
Hmm that's true. I thought we still had them. Then it seems we have some issue in hybrid planning tests:

```
2022-01-03T16:28:44.4474982Z 1: [ros2_control_node-6] [INFO] [1641227319.000744271] [controller_manager]: Loading controller 'joint_state_broadcaster'
2022-01-03T16:28:44.4476585Z 1: [component_container_mt-1] [INFO] [1641227319.002547480] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
2022-01-03T16:28:44.4478071Z 1: [component_container_mt-1] [INFO] [1641227319.012736234] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
2022-01-03T16:28:44.4479559Z 1: [ros2 run controller_manager spawner joint_state_broadcaster-7] [INFO] [1641227319.027879415] [spawner_joint_state_broadcaster]: [94mLoaded joint_state_broadcaster[0m
2022-01-03T16:28:44.4481301Z 1: [component_container_mt-1] [INFO] [1641227319.062178597] [local_planner_component]: Using trajectory operator interface 'moveit_hybrid_planning/SimpleSampler'
2022-01-03T16:28:44.4482741Z 1: [ERROR] [ros2 run controller_manager spawner panda_joint_group_position_controller-8]: process has died [pid 24321, exit code 1, cmd 'ros2 run controller_manager spawner panda_joint_group_position_controller'].
2022-01-03T16:28:44.4484324Z 1: [component_container_mt-1] [INFO] [1641227319.101962209] [local_planner_component]: Using constraint solver interface 'moveit_hybrid_planning/ForwardTrajectory'
2022-01-03T16:28:44.4485685Z 1: [component_container_mt-1] [INFO] [1641227319.107800740] [local_planner_component]: Using 'std_msgs/Float64MultiArray' as local solution topic type
2022-01-03T16:28:44.4487279Z 1: [INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/local_planner' in container '/hybrid_planning_container'
2022-01-03T16:28:44.4488741Z 1: [component_container_mt-1] [INFO] [1641227319.112508165] [hybrid_planning_container]: Load Library: /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_hybrid_planning/lib/libmoveit_hybrid_planning_manager.so.2.3.2
2022-01-03T16:28:44.4490039Z 1: [ros2_control_node-6] [INFO] [1641227319.132255770] [controller_manager]: Configuring controller 'joint_state_broadcaster'
2022-01-03T16:28:44.4493661Z 1: [ros2 run controller_manager spawner joint_state_broadcaster-7] [INFO] [1641227319.151610273] [spawner_joint_state_broadcaster]: [92mConfigured and started [96mjoint_state_broadcaster[0m
2022-01-03T16:28:44.4495511Z 1: [component_container_mt-1] [INFO] [1641227319.164357741] [hybrid_planning_container]: Found class: rclcpp_components::NodeFactoryTemplate<moveit::hybrid_planning::HybridPlanningManager>
2022-01-03T16:28:44.4497544Z 1: [component_container_mt-1] [INFO] [1641227319.165353146] [hybrid_planning_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<moveit::hybrid_planning::HybridPlanningManager>
2022-01-03T16:28:44.4499020Z 1: [INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/hybrid_planning_manager' in container '/hybrid_planning_container'
2022-01-03T16:28:44.4500599Z 1: [component_container_mt-1] [INFO] [1641227319.228844484] [hybrid_planning_manager]: Using planner logic interface 'moveit_hybrid_planning/ReplanInvalidatedTrajectory'
2022-01-03T16:28:44.4502321Z 1: [INFO] [ros2 run controller_manager spawner joint_state_broadcaster-7]: process has finished cleanly [pid 24318]
2022-01-03T16:28:44.4502969Z 1: Waiting for node...
2022-01-03T16:28:44.4503315Z 1: Waiting for node...
2022-01-03T16:28:44.4503672Z 1: Waiting for node...
2022-01-03T16:28:44.4504218Z 1: Waiting for node...
2022-01-03T16:28:44.4504726Z 1: Waiting for node...
2022-01-03T16:28:44.4505255Z 1: Waiting for node...
2022-01-03T16:28:44.4505581Z 1: Waiting for node...
2022-01-03T16:28:44.4505883Z 1: ok
2022-01-03T16:28:44.4506118Z 1: 
2022-01-03T16:28:44.4506685Z 1: ----------------------------------------------------------------------
2022-01-03T16:28:44.4507165Z 1: Ran 1 test in 3.014s
2022-01-03T16:28:44.4507622Z 1: 
2022-01-03T16:28:44.4507863Z 1: OK
2022-01-03T16:28:44.4508687Z 1: [INFO] [ros2_control_node-6]: sending signal 'SIGINT' to process[ros2_control_node-6]
2022-01-03T16:28:44.4509625Z 1: [INFO] [hybrid_planning_demo_node-5]: sending signal 'SIGINT' to process[hybrid_planning_demo_node-5]
2022-01-03T16:28:44.4510584Z 1: [INFO] [robot_state_publisher-4]: sending signal 'SIGINT' to process[robot_state_publisher-4]
2022-01-03T16:28:44.4511768Z 1: [INFO] [static_transform_publisher-2]: sending signal 'SIGINT' to process[static_transform_publisher-2]
2022-01-03T16:28:44.4512726Z 1: [INFO] [component_container_mt-1]: sending signal 'SIGINT' to process[component_container_mt-1]
2022-01-03T16:28:44.4513558Z 1: [ros2_control_node-6] [INFO] [1641227321.386132683] [rclcpp]: signal_handler(signal_value=2)
2022-01-03T16:28:44.4514348Z 1: [hybrid_planning_demo_node-5] [INFO] [1641227321.395413536] [rclcpp]: signal_handler(signal_value=2)
2022-01-03T16:28:44.4515250Z 1: [hybrid_planning_demo_node-5] [INFO] [1641227321.396071633] [test_hybrid_planning_client]: Initialize Planning Scene Monitor
2022-01-03T16:28:44.4516175Z 1: [static_transform_publisher-2] [INFO] [1641227321.398680619] [rclcpp]: signal_handler(signal_value=2)
2022-01-03T16:28:44.4516998Z 1: [robot_state_publisher-4] [INFO] [1641227321.398729219] [rclcpp]: signal_handler(signal_value=2)
2022-01-03T16:28:44.4518169Z 1: [component_container_mt-1] [INFO] [1641227321.402859498] [rclcpp]: signal_handler(signal_value=2)
2022-01-03T16:28:44.4519278Z 1: [hybrid_planning_demo_node-5] [INFO] [1641227321.410363560] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0138244 seconds
2022-01-03T16:28:44.4520323Z 1: [hybrid_planning_demo_node-5] [INFO] [1641227321.410433759] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
2022-01-03T16:28:44.4521784Z 1: [hybrid_planning_demo_node-5] [WARN] [1641227321.426879876] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
2022-01-03T16:28:44.4523293Z 1: [hybrid_planning_demo_node-5] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
2022-01-03T16:28:44.4524716Z 1: [hybrid_planning_demo_node-5]   what():  the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /tmp/binarydeb/ros-galactic-rcl-3.1.2/src/rcl/guard_condition.c:67
2022-01-03T16:28:44.4527616Z 1: [hybrid_planning_demo_node-5] Stack trace (most recent call last) in thread 24344:
2022-01-03T16:28:44.4528719Z 1: [hybrid_planning_demo_node-5] #25   Object "", at 0xffffffffffffffff, in 
2022-01-03T16:28:44.4529890Z 1: [hybrid_planning_demo_node-5] #24   Object "/usr/lib/x86_64-linux-gnu/libc-2.31.so", at 0x7fb986c27292, in __clone
2022-01-03T16:28:44.4530954Z 1: [hybrid_planning_demo_node-5] #23   Object "/usr/lib/x86_64-linux-gnu/libpthread-2.31.so", at 0x7fb986f5c608, in start_thread
2022-01-03T16:28:44.4532047Z 1: [hybrid_planning_demo_node-5] #22   Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28", at 0x7fb986de8de3, in 
2022-01-03T16:28:44.4533420Z 1: [hybrid_planning_demo_node-5] #21 | Source "/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread", line 195, in operator()
2022-01-03T16:28:44.4534487Z 1: [hybrid_planning_demo_node-5]     |   194: 	void
2022-01-03T16:28:44.4535139Z 1: [hybrid_planning_demo_node-5]     | > 195: 	_M_run() { _M_func(); }
2022-01-03T16:28:44.4535764Z 1: [hybrid_planning_demo_node-5]     |   196:       };
2022-01-03T16:28:44.4536648Z 1: [hybrid_planning_demo_node-5]     | Source "/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread", line 251, in _M_invoke<0>
2022-01-03T16:28:44.4537797Z 1: [hybrid_planning_demo_node-5]     |   249: 	  using _Indices
2022-01-03T16:28:44.4538780Z 1: [hybrid_planning_demo_node-5]     |   250: 	    = typename _Build_index_tuple<tuple_size<_Tuple>::value>::__type;
2022-01-03T16:28:44.4539577Z 1: [hybrid_planning_demo_node-5]     | > 251 [...]

2022-01-03 19:06 UTC, vatanaksoytezer commented
Particularly https://github.com/ros-planning/moveit2/blob/595813c6576e1e84b96dd270f5b518fa86501483/moveit_ros/hybrid_planning/test/config/demo_controller.yaml#L8-L9 bit might be incompatible with galactic version of ros2_controllers?

2022-01-03 19:08 UTC, vatanaksoytezer commented
Yeah it seems that bit is released 5 ddays ago but not synced yet, in the meanwhile we can depend on the tag (1.2.0) of source or wait for the sync.

2022-01-03 19:11 UTC, tylerjw commented
> Yeah it seems that bit is released [5 days ago](https://github.com/ros/rosdistro/pull/31626) but not synced yet, in the meanwhile we can depend on the tag (1.2.0) of source or wait for the sync.

Depending on tags in our repos file seems like a good solution.

2022-01-03 19:42 UTC, henningkayser commented
> > Yeah it seems that bit is released [5 days ago](https://github.com/ros/rosdistro/pull/31626) but not synced yet, in the meanwhile we can depend on the tag (1.2.0) of source or wait for the sync.
> 
> Depending on tags in our repos file seems like a good solution.

Unfortunately, this is a perfect way to miss upstream changes. Depending on `-testing` binaries seems like the best way forward for things we don't maintain.

2022-01-06 19:49 UTC, henningkayser commented
@vatanaksoytezer the error you posted is not the reason CI fails. Actually, you can find the same issue on the main jobs (both galactic and rolling). I filed an issue (https://github.com/ros-planning/moveit2/issues/968). Actually, CI should succeed because the branch tests just the same as the main branch. I'll trigger the job again, we possibly just have a flaky test? :thinking:

2022-01-07 10:11 UTC, henningkayser commented
The issue apparently was some side effect of running ccov together with the clang-tidy job. Seems a bit odd to me, but now it passes. Both failing test were focusing on RobotState, maybe we should keep an eye on that.

2022-01-07 10:12 UTC, merged